name: issue-comment-workflow
on: issue_comment

jobs:
  pr-comment:
  # jobs의 실행 조건을 설정할 수 있다.
    if: ${{github.event.issue.pull_request}}
    runs-on: ubuntu-latest
    steps:
    - name: pr comment
      run: echo ${{github.event.issue.pull_request}}

  issue-comment:
    if: ${{!github.event.issue.pull_request}}
    runs-on: ubuntu-latest
    steps:
    - name: issue comment
      run: echo ${{github.event.issue.pull_request}}

