name: pull-request-workflow
on: 
  pull_request:
    # Activity 타입 지정하기 -- ex) pull request가 생성된 시점에 트리거
    types: [opened]

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
    # 멀티라인 커맨드 작성
      run: |
        echo hello world
        echo github action